### ISSUE TITLE
章节任务路线

### ISSUE THREAD

**Issue by ShiningBoy** [gitzxon/yyhelper#4]
章节怪物点击时，每次向右移动选择到尽头之后，向左回返过程中不进行点击怪物，降低了刷怪效率，可以修改

**Comment by gitzxon** [comment]
建议使用新版的脚本。新版脚本使用 atx，基于图像识别技术，可以完美实现章节战斗自动化。
具体内容请查看 Readme 的更新。

**Comment by ShiningBoy** [comment]
谢谢，使用atx后，执行python YysHelper.py -c 10的命令，发现命令卡在
”start to find the image with name chapter10.1920x1080.png”，右侧一直在向上翻动查找章节的图标，但一直找不到。试了其他的章节也都找不到，问题可能出在哪里呢？

**Comment by gitzxon** [comment]
不太好确定具体原因。手机型号是什么？分辨率是多少？
单从现象上看，一直返回这串字符，说明正在手机屏幕上查找 chapter10.1920x1080.png 这个图片，但是失败了。失败的原因可能是没有这个图片，或者查到的图片置信度不够。

**Comment by ShiningBoy** [comment]
是用华为平板BTV-W09,分辨率1600*2560，用现在的atx版本的刷不动，一直都查不到

**Comment by ShiningBoy** [comment]
今天重新试了一下，发现出现运行错误了。具体如下：

Traceback (most recent call last):
  File "YysHelper.py", line 242, in <module>
    main()
  File "YysHelper.py", line 237, in main
    yyshelper.chapter()
  File "YysHelper.py", line 41, in chapter
    chest_find_point = self.d.exists(self.image_name_of_chest)
  File "D:\Python27\lib\site-packages\atx\drivers\mixin.py", line 320, in exists

    ret = self.match(pattern, **match_kwargs)
  File "D:\Python27\lib\site-packages\atx\drivers\mixin.py", line 400, in match
    pattern_scale = self._cal_scale(pattern)
  File "D:\Python27\lib\site-packages\atx\drivers\mixin.py", line 347, in _cal_s
cale
    dw, dh = sorted(self.display)
  File "D:\Python27\lib\site-packages\atx\drivers\android.py", line 185, in disp
lay
    w, h = self.info['displayWidth'], self.info['displayHeight']
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 570, in inf
o
    return self.server.jsonrpc.deviceInfo()
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 408, in wra
pper
    server.start(timeout=30)
  File "D:\Python27\lib\site-packages\uiautomator\__init__.py", line 467, in sta
rt
    raise IOError("RPC server not started!")
IOError: RPC server not started!

没有找到解决办法，求助！

**Comment by mzlogin** [comment]
```sh
IOError: RPC server not started!
```

出现这个是电脑与 Android 设备之间的连接断开了，拔了 USB 线重新连接一下应该能行。

**Comment by ShiningBoy** [comment]
谢谢，现在可以启动，但还是之前的问题，一直在找章节，没法进入。我的平板分辨率是够的，用的也是最新版的代码。

**Comment by gitzxon** [comment]
目前的信息还是不足以定位问题的原因。

手头还有其他手机么，换一个试一试。或者有其他分辨率的比如1920*1080的，也试一试。不过，理论上分辨率不影响使用的，atx 会自动缩放。
